# Inserts a blank line between shell prompts
add_newline = true

# format = """${custom.hostname}$time$cmd_duration$fill$all"""

# Which is equivalent to
format = """${custom.hostname}$time$cmd_duration$fill\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$aws\
$env_var\
$custom\
$sudo\
$line_break\
$jobs\
$battery\
$status\
$shell\
$character"""

[custom.hostname]
command = "echo $HOST_NICKNAME"
when = true
format = "[$output]($style) - "
style = "bold dimmed green"

[fill]
symbol = " "

# Symbols are all from:
# https://starship.rs/presets/#nerd-font-symbols

[aws]
symbol = " "

# All builds are generally done in Docker containers and do not
# use the locally installed compilers, so showing its version
# won't help.
[c]
disabled = true
[cmake]
disabled = true

[character]
success_symbol = "[➜](green)"
error_symbol = "[✗](red)"

[cmd_duration]
min_time = 1_000
format = "- [$duration]($style)"

[directory]
read_only = " "
truncation_length = 4
truncate_to_repo = false
truncation_symbol = ".../"

[docker_context]
symbol = " "
disabled = true

[git_branch]
format = "on [$symbol$branch(:$remote_branch)]($style) "
truncation_length = 20

[git_commit]
commit_hash_length = 8

[git_metrics]
disabled = false

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[golang]
symbol = " "
disabled = true

[hostname]
disabled = true

[java]
symbol = " "
disabled = true

[memory_usage]
symbol = " "

[nix_shell]
symbol = " "
disabled = true

[nodejs]
symbol = " "
disabled = true

[package]
symbol = " "
disabled = true

[perl]
symbol = " "
disabled = true

[python]
symbol = " "
disabled = true

[ruby]
symbol = " "
disabled = true

[rust]
symbol = " "
disabled = true

[time]
format = "[$time]($style) "
time_format = "%F %R"
disabled = false

[username]
disabled = true
