# Inserts a blank line between shell prompts
add_newline = true

format = """$time$fill$all"""
[fill]
symbol = " "

# Symbols are all from:
# https://starship.rs/presets/#nerd-font-symbols

[aws]
symbol = " "

# All builds are generally done in Docker containers and do not
# use the locally installed compilers, so showing its version
# won't help.
[c]
disabled = true
[cmake]
disabled = true

[character]
success_symbol = "[➜](green)"
error_symbol = "[✗](red)"

[cmd_duration]
min_time = 1_000

[directory]
read_only = " "
truncation_length = 4
truncate_to_repo = false
truncation_symbol = ".../"

[docker_context]
symbol = " "

[git_branch]
format = "on [$symbol$branch(:$remote_branch)]($style) "
truncation_length = 20

[git_commit]
commit_hash_length = 8

[git_metrics]
disabled = false

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[golang]
symbol = " "
format = 'via [$symbol]($style)'

[hostname]
ssh_only = false

[java]
symbol = " "

[memory_usage]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
format = 'via [$symbol]($style)'

[package]
symbol = " "

[perl]
symbol = " "
format = 'via [$symbol]($style)'

[python]
symbol = " "
format = 'via [$symbol]($style)'

[ruby]
symbol = " "
format = 'via [$symbol]($style)'

[rust]
symbol = " "
format = 'via [$symbol]($style)'

[time]
format = "[$time]($style) "
time_format = "%F %R"
disabled = false

[username]
disabled = true
