# Inserts a blank line between shell prompts
add_newline = true

format = """${custom.hostname}$time$cmd_duration$fill\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$aws\
$env_var\
$custom\
$sudo\
$line_break\
$jobs\
$battery\
$status\
$shell\
$character"""

[custom.hostname]
command = "echo $HOST_NICKNAME"
when = true
format = "[$output]($style) - "
style = "bold #bd93f9"

[fill]
symbol = " "

# Symbols are all from:
# https://starship.rs/presets/#nerd-font-symbols

[aws]
symbol = " "
style = "bold #ffb86c"

[character]
#success_symbol = "[➜](green)"
#error_symbol = "[✗](red)"
success_symbol = "[➜](bold #50fa7b)"
error_symbol = "[✗](bold #ff5555)"

[cmd_duration]
min_time = 1_000
format = "- [$duration]($style)"
style = "bold #f1fa8c"

[directory]
read_only = " "
truncation_length = 3
truncate_to_repo = false
truncation_symbol = ".../"
style = "bold #50fa7b"

[docker_context]
symbol = " "
disabled = true

[git_branch]
format = "on [$symbol$branch(:$remote_branch)]($style) "
truncation_length = 30
style = "bold #ff79c6"

[git_commit]
commit_hash_length = 8

[git_metrics]
disabled = false

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
style = "bold #ff5555"

[golang]
symbol = " "
disabled = true

[hostname]
style = "bold #bd93f9"
disabled = true

[java]
symbol = " "
disabled = true

[memory_usage]
symbol = " "

[nix_shell]
symbol = " "
disabled = true

[nodejs]
symbol = " "
disabled = true

[package]
symbol = " "
disabled = true

[perl]
symbol = " "
disabled = true

[python]
symbol = " "
disabled = true

[ruby]
symbol = " "
disabled = true

[rust]
symbol = " "
disabled = true

[time]
format = "[$time]($style) "
time_format = "%F %R"
disabled = false

[username]
format = "[$user]($style) on "
style_user = "bold #8be9fd"
disabled = true
