import = ["~/.config/alacritty/solarized_light.toml"]
live_config_reload = true

[shell]
args = ["--login"]
program = "/Users/jpeacock/.nix-profile/bin/fish"

[window]
decorations = "None"
[window.position]
x = 0
y = 0
[window.dimensions]
columns = 307
lines = 101

[font]
size = 12.0
[font.bold]
family = "GoMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "GoMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "GoMono Nerd Font"
style = "Italic"

[font.normal]
family = "GoMono Nerd Font"
style = "Book"
