import = ["~/.config/alacritty/solarized_dark.toml"]
live_config_reload = true

[shell]
args = ["--login"]
program = "/Users/jasonpeacock/.nix-profile/bin/fish"

[window]
decorations = "None"
[window.position]
x = 0
y = 0
[window.dimensions]
columns = 120
lines = 40

[font]
size = 14.0

# family = "GoMono Nerd Font" # Serif
# family = "JetBrainsMono Nerd Font Mono"
# family = "IosevkaTermSlab Nerd Font Mono" # Serif
# family = "Hurmit Nerd Font"
# family = "IntoneMono Nerd Font"
# family = "FiraCode Nerd Font Mono" # No italic
# family = "Monoid NFM"
# family = "SauceCodePro Nerd Font Mono" # only Regular
# family = "ImWritingMono Nerd Font Mono"
[font.normal]
family = "IosevkaTermSlab Nerd Font Mono" # Serif
style = "Light"

[font.italic]
family = "IosevkaTermSlab Nerd Font Mono" # Serif
style = "Light Italic"

[font.bold]
family = "IosevkaTermSlab Nerd Font Mono" # Serif
style = "Regular"

[font.bold_italic]
family = "IosevkaTermSlab Nerd Font Mono" # Serif
style = "Italic"
