import = ["~/.config/alacritty/solarized_light.toml"]
live_config_reload = true

[shell]
args = ["--login"]
program = "/Users/jpeacock/.nix-profile/bin/fish"

[window]
decorations = "None"
[window.position]
x = 0
y = 0
[window.dimensions]
columns = 120
lines = 40

[font]
size = 14.0
[font.bold]
# family = "GoMono Nerd Font" # Serif
# family = "JetBrainsMono Nerd Font Mono" # SansSerif
family = "IosevkaTermSlab Nerd Font Mono" # Serif
style = "Regular" # Bold

[font.bold_italic]
family = "IosevkaTermSlab Nerd Font Mono"
style = "Italic" # Bold Italic

[font.italic]
family = "IosevkaTermSlab Nerd Font Mono"
style = "Light Italic" # Italic

[font.normal]
family = "IosevkaTermSlab Nerd Font Mono"
style = "Light" # Regular
